spring:
  application:
    name: psychology_back
  datasource:
    url: jdbc:postgresql://localhost:5432/psychology
    username: setlocal
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:migration/db.changelog-master.yml