--liquibase formatted sql

--changeset 20240606123000 author:belchikdm
--comment: #1 create new table test

create table test
(
    id          bigint generated by default as identity
        constraint test_pkey primary key,
    title       varchar(255),
    description varchar(255)
);

insert into test (title, description)
values ('EOMS Шелла',
        'Методика предназначена для определения копинг-механизмов, направленности мышления при решении сложных ' ||
        'задач в различных сферах деятельности, отношения к сложившимся обстоятельствам.'),
       ('Для теста', 'Для теста.');